### ISSUE TITLE
User-can-view-most-recent-data-for-default-location

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/ajax-project#2]
## 💰 Motivation

User will want to view default information on the home page.

## 📐 Plan

Create a view where the user can see information regarding food recalls

## 🖼️ Wireframe

![user can view the homepage]
![image](https://user-images.githubusercontent.com/6721652/102286325-ecbdd580-3eec-11eb-80ca-812a5bb64b38.png)

## ✅ Task List

- [x] Create a HTML skeleton
- [x] Create a presentable view with HTML and CSS
- [x] Create a form to send start date, end date, and location
- [x] Create a function that utilizes the openFDA API
- [x] Create a dynamic div that populates information retrieved from API
- [x] Remove all unused CSS
- [x] Test features
- [x] Fix bugs
- [x] Test features again
