### ISSUE TITLE
User-can-filter-recalls-by-date

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/ajax-project#4]
## 💰 Motivation

User will be able to search for recalls within a specific date time frame

## 📐 Plan

Create a function that retrieves information from the given date

## ✅ Task List

- [x] Create a function that will get recalls based on date
- [x] Listen for submit event and pass date data to function
- [x] Render those recalls
- [x] Remove unused CSS
- [x] Test Functionality
- [x] Fix Bugs
- [x] Test again
