### ISSUE TITLE
User-can-view-a-list-of-recalls-using-all-search-parameters

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/ajax-project#5]
## 💰 Motivation

User will want to search with all criteria

## 📐 Plan

Create a function that can GET data from the API using all user inputted fields

## ✅ Task List

- [x] Create a URL creation function
- [x] Modify the submit listener to check for empty fields and send to the URL creation function
- [x] Create a function that sends all parameters in the XMLHttpRequest
- [x] Test
- [x] Fix bugs
- [x] Test again
