### ISSUE TITLE
User-can-view-full-details-of-recall

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/ajax-project#6]
## 💰 Motivation

Users will want to see more information regarding the recall

## 📐 Plan

Create a separate view that dynamically renders the recalls information from the API

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/6721652/102286997-52f72800-3eee-11eb-9e78-85dade8ec0e7.png)

## ✅ Task List

- [x] Create another view for details
- [x] Add event listener for "clicks"
- [x] Populate new view with information from the clicked recall
- [x] Test
- [x] Fix bugs
- [x] Test again
